---
version: "2.4"
volumes:
  smartweb-postgres:
services:
  instance:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    links:
      - postgres:db
    depends_on:
      - postgres
      - solr
    volumes:
      - ./zodbconvert.cfg:/plone/zodbconvert.cfg
    environment:
      - MEMCACHE_SERVER=172.17.0.1
      - MEMCACHE_DEFAULT_AGE=10800
      - ENV=dev
      - CACHING_SERVERS=varnish.staging.imio.be:5000
      - DOMAINS=localhost
      - RELSTORAGE_DB=zope
      - RELSTORAGE_USER=zope
      - RELSTORAGE_PASSWORD=zope
      - RELSTORAGE_HOSTNAME=db
      - RELSTORAGE_PORT=5432
      - ZODB_CACHE_SIZE=30000
      - ZEO_CLIENT_CACHE_SIZE=256MB
      - PROJECT_ID=test
      - PLONE_EXTENSION_IDS=plone.app.caching:default,plonetheme.barceloneta:default,imio.smartweb.policy:default
      - DEFAULT_LANGUAGE=fr
      - ACTIVE_BIGBANG=True
      - COLLECTIVE_SOLR_HOST=solr
      - COLLECTIVE_SOLR_PORT=8983
      - COLLECTIVE_SOLR_BASE=/solr/web
      - COLLECTIVE_SOLR_LOGIN=solr
      - COLLECTIVE_SOLR_PASSWORD=SolrRocks
      - service_ou=0841470248
      - service_slug=local-iasmartweb
      - consumer_key_agents=6ccfcf9c-f587-4bf1-9491-b31382a4d461
      - consumer_secret_agents=bfb6e1e6-a6e1-48fe-a44c-9cab652bb0db
      - authentic_usagers_hostname=usagers.staging.imio.be
      - authentic_agents_hostname=agents.staging.imio.be

    healthcheck:
      test: ["CMD", "nc", "-z", "-w5", "127.0.0.1", "8080"]
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.instance.rule=Host(`portal.localhost`)"
      - "traefik.http.services.instance.loadbalancer.server.port=8080"
      - "traefik.http.routers.instance.middlewares=add-plone"
      - "traefik.http.middlewares.add-plone.addprefix.prefix=/VirtualHostBase/http/portal.localhost:8080/Plone/VirtualHostRoot"
  reverse-proxy:
    image: traefik:v2.4
    command: --api.insecure=true --providers.docker
    ports:
      - "80:80" # The HTTP port
      - "8001:8080" # The Web UI (enabled by --api)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # So that Traefik can listen to the Docker events
  postgres:
    image: postgres:14.2
    environment:
      - POSTGRES_DB=zope
      - POSTGRES_USER=zope
      - POSTGRES_PASSWORD=zope
    volumes:
      - smartweb-postgres:/var/lib/postgresql/data
  memcached:
    image: memcached:1.5.20
    command:
      - "-m"
      - "1024"
  solr:
    image: solr:9.6.1-slim
    ports:
      - "8983:8983"
    volumes:
      - ./solr:/var/solr/data/plone
