name: Publish and deploy dev image
on:
  push:
    branches:
      - dev
    tags:
      - '!**'
  workflow_dispatch:
env:
  IMAGE_NAME: 'web/smartweb/mutual'
  REGISTRY_URL: ${{ secrets.HARBOR_URL }}

jobs:
  build-push:
    runs-on: gha-runners-smartweb
    if: contains(github.event.head_commit.message, 'Back to development:') == false && contains(github.event.head_commit.message, 'Preparing release') == false
    steps:
      - name: Build tags
        run: |
          {
            echo 'IMAGE_TAGS<<EOF'
            echo '${{ env.REGISTRY_URL }}/${{ env.IMAGE_NAME }}:dev'
            echo '${{ env.REGISTRY_URL }}/${{ env.IMAGE_NAME }}:dev-${{ github.run_number }}'
            echo EOF
          } >> $GITHUB_ENV
      - name: Build push and notify
        uses: IMIO/gha/build-push-notify@v3.9.3
        with:
          IMAGE_NAME: ${{ env.IMAGE_NAME }}
          IMAGE_TAGS: ${{ env.IMAGE_TAGS }}
          REGISTRY_URL: ${{ env.REGISTRY_URL}}
          REGISTRY_USERNAME: ${{ secrets.SMARTWEB_HARBOR_USERNAME }}
          REGISTRY_PASSWORD: ${{ secrets.SMARTWEB_HARBOR_PASSWORD }}
          MATTERMOST_WEBHOOK_URL: ${{ secrets.SMARTWEB_MATTERMOST_WEBHOOK_URL }}
  deploy:
    runs-on: gha-runners-smartweb
    needs: build-push
    steps:
      - name: Deploy to dev and notify
        uses: IMIO/gha/rundeck-notify@v3.9.3
        with:
          RUNDECK_URL: ${{ secrets.RUNDECK_URL }}
          RUNDECK_TOKEN: ${{ secrets.SMARTWEB_RUNDECK_TOKEN }}
          RUNDECK_JOB_ID: ${{ secrets.RUNDECK_DEPLOY_DEV_JOB_ID }}
          RUNDECK_PARAMETERS: '-X POST'
          MATTERMOST_WEBHOOK_URL: ${{ secrets.SMARTWEB_MATTERMOST_WEBHOOK_URL }}
